spring.application.name=paymentService
spring.config.import=optional:configserver:http://localhost:8092

razorpay.key.id:rzp_test_ST7fkBzhNdwbR5
razorpay.key.secret:5GsuHVSKTug3aaCS9xu2YmHL
stripe.apikey:sk_test_51RSaHJPBV5c9jYdKjwOlk65Zmuoiqe9mPRmAKPYpFvZ83kzjJeGowt9CThyRpzhUGPDS0f263l4fKVBrjS7FF6Q400VU6VNKud

